import {
  Anchor,
  Armchair,
  Bath,
  Beef,
  Beer,
  Bike,
  BookOpen,
  Cake,
  Camera,
  ChefHat,
  Clapperboard,
  Coffee,
  Compass,
  CookingPot,
  Dices,
  Disc3,
  Drama,
  Drum,
  Dumbbell,
  Film,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  GlassWater,
  Guitar,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Map,
  Martini,
  Mic,
  Moon,
  Mountain,
  Music,
  Palette,
  PartyPopper,
  Pizza,
  Popcorn,
  Puzzle,
  Sailboat,
  Salad,
  Sandwich,
  ShoppingBag,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Star,
  Sunset,
  Telescope,
  Tent,
  Theater,
  Ticket,
  TreePine,
  Trophy,
  Tv,
  UtensilsCrossed,
  Users,
  Wine,
  type LucideIcon,
} from 'lucide-react'
import type { ReactNode } from 'react'

/**
 * Curated lucide-react icons covering common evening activities. The keys are
 * the names the AI picks from (exposed via {@link ACTIVITY_ICON_NAMES}) and the
 * same names the seed deck uses — keep them in sync if you add icons.
 */
export const ACTIVITY_ICONS: Record<string, LucideIcon> = {
  // Food & drink
  Wine,
  Beer,
  Martini,
  GlassWater,
  Coffee,
  UtensilsCrossed,
  Pizza,
  Soup,
  Sandwich,
  Beef,
  Fish,
  Salad,
  IceCreamCone,
  Cake,
  CookingPot,
  ChefHat,
  // Nightlife & music
  Music,
  Disc3,
  Guitar,
  Drum,
  Mic,
  Headphones,
  PartyPopper,
  // Screen & shows
  Film,
  Clapperboard,
  Popcorn,
  Tv,
  Theater,
  Drama,
  Ticket,
  // Games
  Gamepad2,
  Dices,
  Puzzle,
  Trophy,
  // Creative & culture
  Palette,
  Camera,
  BookOpen,
  // Outdoors & active
  Footprints,
  Bike,
  Mountain,
  Tent,
  TreePine,
  Telescope,
  Flame,
  Dumbbell,
  Sailboat,
  Anchor,
  Compass,
  Map,
  Snowflake,
  Flower2,
  // Vibe & home
  Heart,
  Users,
  House,
  Sofa,
  Armchair,
  Bath,
  ShoppingBag,
  Moon,
  Star,
  Sunset,
  Sparkles,
}

/** Allowed icon names — the structured-output enum and what the model picks from. */
export const ACTIVITY_ICON_NAMES = Object.keys(ACTIVITY_ICONS)

/** Render an activity's icon by name, falling back to a sparkle when unknown. */
export function activityIcon(name: string | undefined, className = 'size-6'): ReactNode {
  const Icon = (name && ACTIVITY_ICONS[name]) || Sparkles
  return <Icon className={className} strokeWidth={1.75} aria-hidden />
}
